# Address:port to listen on
listen = ":9876"

# This should be set to the address accessible from API clients
export_address = "localhost"

# Port range for exposed containers
ports_range = [20000, 30000]

# Only `docker` is available at the moment
container_engine = "docker"

# Template settings
[tpl]
# Base dir where all template files will be located
base_dir = "/opt/xenvman/tpl"
# Base directory where all image workspace dirs will be created
ws_dir = "/opt/xenvman/ws"
# Base directory
mount_dir = "/opt/xenvman/mount"

[tls]
# Path to certificate file
cert = ""
# Path to key file
key = ""

## Log settings
[log]
# For the format description take a look here:
# https://github.com/juju/loggo#func-configureloggers
config = "<root>=trace"
